import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="bg-red-500 flex gap-5 item-center justify-center">
            <li>home</li>
            <li>about</li>
            <li>contac</li>
          </ul>
        </nav>
        {children}
        <footer className="bg-green-400">
          <h2>all right reserver @2024</h2>
        </footer>
        </body>
    </html>
  );
}
